### ISSUE TITLE
UVG dataset reproduce

### ISSUE THREAD

**Issue by subinKim14** [haochen-rye/NeRV#12]
Hello, I have one question about reproducing the results, especially UVG.

To train NeRV for UVG dataset, I set the command as follows:

python train_nerv.py -e 150   --lower-width 96 --num-blocks 1 --dataset PATH --frame_gap 1 --outf bunny_ab --embed 1.25_80 --stem_dim_num 512_1  --reduction 2  --fc_hw_dim 9_16_112 --expansion 1  --single_res --loss Fusion6   --warmup 0.2 --lr_type cosine  --strides 5 3 2 2 2   --conv_type conv  -b 1  --lr 0.0005 --norm none --act gelu

Is there any suggestion for accurate reproduced results?

Thank you :)

**Comment by haochen-rye** [comment]
With `--fc_hw_dim 9_16_112 --expansion 1`, most of your parameters would be in the FC layer (I would suggest giving slightly more parameters to Conv layers) . 
Btw, setting` --lower-width 96 ` might introduce lots of FLOPs in NeRV blocks with `1080p` resolution feature map

**Comment by subinKim14** [comment]
Thanks for your suggestion. 

Btw, **could you recommend the exact parameter settings** to reproduce the results?
You might know the better parameter settings than I do. 

Thank you :)

**Comment by haochen-rye** [comment]
I list the setups [here](https://github.com/haochen-rye/NeRV/issues/11#issue-1211790431).
