### ISSUE TITLE
Interpolating between two frames

### ISSUE THREAD

**Issue by Alpe6825** [haochen-rye/NeRV#14]
hi,  

I'm interested in interpolating between frames. In the appendix A.4 of the paper there is a figure where you interpolate between two seen frames. I tried to reproduced that with your pretrained model but there are strong artifacts in the result:

![pred_5](https://user-images.githubusercontent.com/51789043/174840671-a093e791-d162-46f6-bcb8-274a39dab6b5.png)

The only thing i changed was `embed_input = pe(norm_idx+(1/132)*0.5)` in train_nerv.py l. 484. Is there something I didn't notice for reproducing the interpolation? I would be glad for any hint.

Its a great work and i saw there is a follow up paper in review, that seems to focus that problem too, right? Are there any planes for a approx. release date?

**Comment by haochen-rye** [comment]
For frame interpolation, unfortunately, NeRV cannot do it well, just as you saw. And that’s why I propose GNeRV and HNeRV to enable better generalization and enable frame  interpolation. Actually the code is ready to release as long as the papers get accepted (maybe after ICLR).
