### ISSUE TITLE
Possible mistake in ReadMe

### ISSUE THREAD

**Issue by CarlosGomes98** [haochen-rye/NeRV#17]
Hi,

I think I may have found some mistake in the Readme (or in the paper, but I believe it is just the readme)

From the paper, I see that you choose to prune away 40% of the weights.

From the code, the prune_ratio parameter seems to mean the proportion of weights that are kept, as 1-prune_ratio is passed to the pytorch prune function as the amount parameter.

In the final section of the ReadME, you calculate bpp using 1 - prune_ratio however. Should this not be just prune_ratio? or 1-model_sparsity.

Furthermore, am I correct in thinking the value of the prune_ratio parameter to replicate the results in the paper should be 0.6, unlike the 0.4 in the ReadMe?

Thanks for any clarifications.

**Comment by haochen-rye** [comment]
Yeah, you are right, it should be (1-Model_Sparsity) in readme when compute BPP, thanks for your help. 
And when sparsity is 0.4, the prune ratio should be 0.6.
