### ISSUE TITLE
Missing UVG video identifiers

### ISSUE THREAD

**Issue by aegroto** [haochen-rye/NeRV#18]
Hello, thanks again for sharing the results of your research!

I would like to make use of the results listed in psnr_bpp_results.csv for comparison, but I can't figure out which video relates to each line in the CSV file. The UVG dataset itself is bigger than the amount of results (7) listed in the first half.

Could you please add the video names in the first column? Thanks.

**Comment by haochen-rye** [comment]
Hi,

I don't have per-video results for NeRV, numbers in the CSV file are for the whole UVG dataset (we concat all 7 videos as a long video and use one model to represent it)

**Comment by aegroto** [comment]
Hello,

Thanks for your reply @haochen-rye. What are the 7 videos you are using for your experiments? As far as I could see from the UVG website they have released more than 7.

**Comment by maoqingyu1996** [comment]
> 
Hi,
The authors stated that they used 1080P video from UVG data for the experiment. As a result, only seven videos were used, and no other videos with only 4K resolution were used.
