### ISSUE TITLE
Lack of instructions for decoding

### ISSUE THREAD

**Issue by aegroto** [haochen-rye/NeRV#4]
Hello,

I would like to thank you for sharing your work, it's a very interesting concept and I can see a lot of promising research on the subject to be done in the future.

I've got a doubt about the decoding part, is there already a way to convert the resulting neural network back to a sequence of frames?

**Comment by haochen-rye** [comment]
Update README with decoding instructions at:
https://github.com/haochen-rye/NeRV/blob/master/README.md#decoding-dump-predictions-with-pre-trained-model

**Comment by aegroto** [comment]
Sorry if I comment on this again, but I can see that the dumped frames do not reflect the original resolution of the video. Is there some parameter I have to set to explicitly specify the width and height of the video while training/evaluating?
