### ISSUE TITLE
Distrotion-Compression result

### ISSUE THREAD

**Issue by subinKim14** [haochen-rye/NeRV#6]
Hello, I really appreciate your impressive work.

I have one question about calculating bits per pixel. 

You mentioned that bpp is calculated as follows: Model_Parameter∗(1−Prune_Ratio)∗Quant_Bit/Pixel_Num

Here, Pixel_Num means what?
For example, if we have a video, which has 100 frames of 720x1280 resolution.
1) number of frames * width * height (100x720x1280)
2) width * height (720x1280)

Thanks.

**Comment by haochen-rye** [comment]
Since all frames are stored in one video, so pixel_num should all video pixels (i.e. your choice 1):
`number of frames * width * height (100x720x1280)`

**Comment by subinKim14** [comment]
Thanks for your quick and clear reply :)  Also, I have one more question. 
Do we need to multiply channels numbers for "Pixel_Num" ? 
For example, if a video has RGB colors, I think we need to multiply  
number of frames * width * height * channels (100x720x1280x3).

Thanks.

**Comment by GZY2000** [comment]
> Thanks for your quick and clear reply :) Also, I have one more question. Do we need to multiply channels numbers for "Pixel_Num" ? For example, if a video has RGB colors, I think we need to multiply number of frames * width * height * channels (100x720x1280x3).
> 
> Thanks.

Hello, how is the value "Model_Parameter" calculated?
