### ISSUE TITLE
Bpp calculation

### ISSUE THREAD

**Issue by subinKim14** [haochen-rye/NeRV#8]
Hello,

I really appreciate for sharing your work.

I have some question about the decoding part. How did you calculate the BPP when encoding with the traditional codec, such as HECV?

In appendix, only the commands to compress videos with H.264 or HEVC codec under medium preset are described.

If you do not mind, please explain the details to calculate the bpp precisely.

Thanks.

**Comment by haochen-rye** [comment]
Sure, below is the app for traditional codec (for python):
```
    vid_size = os.path.getsize(new_vid)  * 8       # getsize() return video size in Bytes, *8 to convert size to bits
    vid_bpp = vid_size / frame_size / frame_num   # frame_size the pixel_num for each frame, frame_num is the video length         
```
